# TinyML ECG Classification

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

## Read Dataset

In [2]:
!pip install kaggle
!mkdir ~/.kaggle
!cp /content/kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
# !kaggle competitions download -c diabetes-classification
!kaggle datasets download -d shayanfazeli/heartbeat

 98% 97.0M/98.8M [00:01<00:00, 101MB/s] 
100% 98.8M/98.8M [00:01<00:00, 80.6MB/s]


In [4]:
!unzip /content/heartbeat.zip

Archive:  /content/heartbeat.zip
  inflating: mitbih_test.csv         
  inflating: mitbih_train.csv        
  inflating: ptbdb_abnormal.csv      
  inflating: ptbdb_normal.csv        


In [7]:
df_train = pd.read_csv("/content/mitbih_train.csv", header=None)
df_test = pd.read_csv("/content/mitbih_test.csv", header=None)
df_test_x = pd.read_csv("/content/testdata.csv")
df_train.head()

0         1         2         3         4         5         6    \
0  0.977941  0.926471  0.681373  0.245098  0.154412  0.191176  0.151961   
1  0.960114  0.863248  0.461538  0.196581  0.094017  0.125356  0.099715   
2  1.000000  0.659459  0.186486  0.070270  0.070270  0.059459  0.056757   
3  0.925414  0.665746  0.541436  0.276243  0.196133  0.077348  0.071823   
4  0.967136  1.000000  0.830986  0.586854  0.356808  0.248826  0.145540   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.085784  0.058824  0.049020  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.088319  0.074074  0.082621  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.043243  0.054054  0.045946  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.060773  0.066298  0.058011  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.089202  0.117371  0.150235  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 188 columns]

In [8]:
# df[187] is y (class 0~4)
print(df_train[187].value_counts())
print(df_test[187].value_counts())

0.0    72471
4.0     6431
2.0     5788
1.0     2223
3.0      641
Name: 187, dtype: int64
0.0    18118
4.0     1608
2.0     1448
1.0      556
3.0      162
Name: 187, dtype: int64


In [ ]:
df_test[0][0] = 1.0

## Prepare Dataset

In [9]:
X_train = df_train.values[:, :-1]
y_train = df_train.values[:, -1].astype(int)

X_test  = df_test.values[:, :-1]
y_test  = df_test.values[:, -1].astype(int)

# testx,testy = df_test.values[:,-1]
testx,testy = df_test_x.values[:,:-1],df_test_x.values[:,-1].astype(int)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(testx.shape)
print(testy.shape)

(87554, 187)
(21892, 187)
(87554,)
(21892,)
(14, 187)
(14,)


In [ ]:
# print(x_test.shape)
# print(y_test.shape)

NameError: ignored

In [ ]:
# y_test

array([0, 0, 0, ..., 4, 4, 4])

In [10]:
# reshape for Conv2D
x_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1, 1)
x_test = X_test.reshape(X_test.shape[0], X_test.shape[1],1, 1)
testx = testx.reshape(testx.shape[0],testx.shape[1],1,1)
print(x_train.shape)
print(x_test.shape)
print(testx.shape)

(87554, 187, 1, 1)
(21892, 187, 1, 1)
(14, 187, 1, 1)


In [ ]:
# print(y_train.shape)
# print(y_test.shape)
# print(testy.shape)
# testy = testy.reshape(testy.shape[0],5)
# print(testy.shape)

(87554,)
(21877,)
(14,)


ValueError: ignored

In [11]:
from tensorflow.keras import utils
y_train = utils.to_categorical(y_train)
y_test  = utils.to_categorical(y_test)
testy = utils.to_categorical(testy,num_classes=5)
print(y_train.shape)
print(y_test.shape)
print(testy.shape)


(87554, 5)
(21892, 5)
(14, 5)


## Build Model

In [24]:
type(x_test)

numpy.ndarray

In [33]:
list(y_test[0]).index(1)

0

In [12]:
input_shape = x_train.shape[1:]
num_classes= 5

In [ ]:
# Build Model 
# from tensorflow.keras import models, layers
import keras 
from keras import models,layers
inputs = layers.Input(shape=input_shape)
x = layers.Conv2D(16, kernel_size=5, activation='relu', padding='same')(inputs)
#x = layers.Conv2D(16, kernel_size=5, activation='relu', padding='same')(x)
#x = layers.MaxPooling2D((2,2), padding='same')(x)

x = layers.Flatten()(x)
x = layers.Dense(16)(x)
outputs = layers.Dense(num_classes, activation="softmax")(x)

model = models.Model(inputs=inputs, outputs=outputs)

model.summary()

Model: "model_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_8 (InputLayer)        [(None, 187, 1, 1)]       0         
                                                                 
 conv2d_7 (Conv2D)           (None, 187, 1, 16)        416       
                                                                 
 flatten_7 (Flatten)         (None, 2992)              0         
                                                                 
 dense_14 (Dense)            (None, 16)                47888     
                                                                 
 dense_15 (Dense)            (None, 5)                 85        
                                                                 
Total params: 48,389
Trainable params: 48,389
Non-trainable params: 0
_________________________________________________________________


In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer, Conv2D, Flatten, Dense
smodel = Sequential()
smodel.add(InputLayer(input_shape=input_shape))
smodel.add(Conv2D(16, kernel_size=5, activation='relu', padding='same'))
smodel.add(Flatten())
smodel.add(Dense(16))
smodel.add(Dense(num_classes,activation='softmax'))

In [14]:
# Compile Model
smodel.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# # Compile Model
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

## Train Model

In [15]:
batch_size = 100
num_epochs = 10 

In [16]:
# Train Model
shistory = smodel.fit(x_train, y_train, epochs=num_epochs, batch_size=batch_size, validation_data=(testx,testy))
# shistory = smodel.fit(x_train, y_train, epochs=num_epochs, batch_size=batch_size, validation_data=(testx, testy))

Epoch 1/10
876/876 [==============================] - 13s 14ms/step - loss: 0.3716 - accuracy: 0.8924 - val_loss: 0.0685 - val_accuracy: 1.0000
Epoch 2/10
876/876 [==============================] - 12s 13ms/step - loss: 0.1951 - accuracy: 0.9476 - val_loss: 0.0699 - val_accuracy: 1.0000
Epoch 3/10
876/876 [==============================] - 13s 14ms/step - loss: 0.1608 - accuracy: 0.9568 - val_loss: 0.0912 - val_accuracy: 1.0000
Epoch 4/10
876/876 [==============================] - 12s 14ms/step - loss: 0.1496 - accuracy: 0.9592 - val_loss: 0.0425 - val_accuracy: 1.0000
Epoch 5/10
876/876 [==============================] - 14s 16ms/step - loss: 0.1418 - accuracy: 0.9613 - val_loss: 0.0316 - val_accuracy: 1.0000
Epoch 6/10
876/876 [==============================] - 12s 14ms/step - loss: 0.1347 - accuracy: 0.9634 - val_loss: 0.0175 - val_accuracy: 1.0000
Epoch 7/10
876/876 [==============================] - 12s 14ms/step - loss: 0.1325 - accuracy: 0.9636 - val_loss: 0.0308 - val_accuracy:

In [33]:

# Train Model
history = model.fit(x_train, y_train, epochs=num_epochs, batch_size=batch_size, validation_data=(x_test, y_test))

NameError: ignored

## Save Model

In [34]:
# Save Model
models.save_model(model, 'ecg_cnn.hdf5')

NameError: ignored

In [17]:
score = smodel.evaluate(x_test,y_test,verbose=2)

685/685 - 2s - loss: 0.1368 - accuracy: 0.9640 - 2s/epoch - 3ms/step


In [18]:
score


[0.1367604285478592, 0.9640051126480103]

In [19]:
predct = smodel.predict(x_test)

In [20]:
predct

array([[9.9278224e-01, 7.1713459e-03, 2.2685770e-08, 4.6161924e-05,
        2.0613447e-07],
       [9.8491883e-01, 1.0429059e-02, 2.2839569e-03, 4.6058194e-04,
        1.9075049e-03],
       [9.2840344e-01, 3.5731561e-02, 7.9822867e-06, 1.3720023e-04,
        3.5719808e-02],
       ...,
       [5.2983359e-02, 2.8737178e-03, 1.8313864e-02, 2.4586177e-04,
        9.2558324e-01],
       [6.4348773e-05, 9.1623169e-06, 1.9031258e-05, 5.7498774e-08,
        9.9990737e-01],
       [2.1923285e-04, 1.0725963e-06, 4.7385850e-04, 1.1474989e-07,
        9.9930573e-01]], dtype=float32)

In [21]:
predct.shape

(21892, 5)

In [22]:
for i in predct:
  for j in range(len(i)):
    i[j] = i[j].round()

In [23]:
predct

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]], dtype=float32)